# Generated by Django 5.0 on 2026-05-22 07:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='ای دی کاربر', primary_key=True, serialize=False, unique=True, verbose_name='ای دی کاربر')),
                ('username', models.CharField(blank=True, db_index=True, help_text='username را وارد کنید', max_length=20, null=True, verbose_name='username')),
                ('first_name', models.CharField(blank=True, db_index=True, help_text='اسم را وارد کنید', max_length=20, null=True, verbose_name='اسم')),
                ('last_name', models.CharField(blank=True, db_index=True, help_text='نام خوانوادگی را وارد کنید', max_length=20, null=True, verbose_name='نام خوانوادگی')),
                ('email', models.EmailField(blank=True, db_index=True, help_text='ایمیل خود را وارد کنید', max_length=100, null=True, unique=True, verbose_name='ایمیل')),
                ('phone_number', models.CharField(help_text='شماره تلفن خود راوارد کنید', max_length=11, unique=True, verbose_name='شماره تلفن')),
                ('date_joined', models.DateTimeField(auto_now_add=True, db_index=True, help_text='تاریخ جوین شدن', verbose_name='تاریخ ساخنه شدن')),
                ('user_ip', models.GenericIPAddressField(blank=True, db_index=True, help_text='ای پی user', null=True, verbose_name='ای پی user')),
                ('last_login', models.DateTimeField(auto_now_add=True, db_index=True, help_text=' اخرین زمان ورود', verbose_name='تاریخ اخرین ورود')),
                ('is_admin', models.BooleanField(db_index=True, default=False, help_text='کاربر ادمین هست ', verbose_name='ادمین')),
                ('is_active', models.BooleanField(db_index=True, default=False, help_text='کاربر فعال هست', verbose_name='کاربر فعال')),
                ('is_staff', models.BooleanField(db_index=True, default=False, help_text='کاربر مدیر هست', verbose_name='کاربر مدیر')),
                ('is_superuser', models.BooleanField(db_index=True, default=False, help_text=' کاربر سوپر یوزراست', verbose_name='کاربر سوپر یوزر')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='زمان ساخت', null=True, verbose_name='زمان ساخت')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, help_text='زمان ارتقا', null=True, verbose_name='زمان ارتقا')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربران',
                'verbose_name_plural': 'کاربران',
                'ordering': ['created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('mapping', models.JSONField()),
                ('insights', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reports',
            },
        ),
    ]
