# Generated by Django 5.0 on 2026-05-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='شماره تلفن خود راوارد کنید', max_length=11, null=True, verbose_name='شماره تلفن'),
        ),
    ]
